# Generated by Django 4.2.5 on 2023-12-22 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_alter_listing_cateogry'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='cateogry',
            new_name='category',
        ),
    ]
